### ISSUE TITLE
gapps missing

### ISSUE THREAD

**Issue by berndhofer** [supechicken/waydroid-androidtv-build#10]
Hi there. The image itself is running great, but I am unable to initialize your custom gapps. I created the system subfolder etc. but no success. Also the google play cert leads to an error:

id.gsf/databases/gservices.db "select * from main where name = \"android_id\";"                    <
Error: unable to open database "/data/data/com.google.android.gsf/databases/gservices.db": unable to open database file

**Comment by supechicken** [comment]
Boot the container once and try again?

**Comment by viell-dev** [comment]
Try running `sudo waydroid init -f` again. That worked for me.

**Comment by supechicken** [comment]
Closing as unable to reproduce.
