### ISSUE TITLE
Black screen in YouTube app 

### ISSUE THREAD

**Issue by AmongUS987** [supechicken/waydroid-androidtv-build#12]
YouTube apps play video, but screen is black
![IMG_3260](https://github.com/user-attachments/assets/659a0da8-4a87-4552-931a-09dfc410e7cb)

**Comment by supechicken** [comment]
Hello, could you please try the [latest build](https://github.com/supechicken/waydroid-androidtv-build/releases/tag/20241208) and see if it works?

**Comment by supechicken** [comment]
Closing as no response.
