### ISSUE TITLE
"Notification" card and nothing else

### ISSUE THREAD

**Issue by FelixOnly** [supechicken/waydroid-androidtv-build#13]
![image](https://github.com/user-attachments/assets/ec32d714-7614-489e-8c18-8c99c6d44cd2)

Hello! Thank you for yuor project, I have problem after installation there just notification's card and nothing else, after maybe 10 minutes, it is gone and there is just black screen

**Comment by supechicken** [comment]
Press <kbd>Esc</kbd> and you will be dropped into the launcher.

I am not sure why GitHub deleted the previously similar issue on this:
![image](https://github.com/user-attachments/assets/1a117668-31dd-4d61-b0ec-52f72da70a1c)

**Comment by FelixOnly** [comment]
Big thank you!! 😄
