### ISSUE TITLE
ATV 13 can't login 

### ISSUE THREAD

**Issue by FelixOnly** [supechicken/waydroid-androidtv-build#14]
Hello, I tried ATV 11; it was working okay, but I decided to use ATV 13 instead. 

My actions after installing ATV 11.
1. Wiped all previous data. 
3. Installed system ATV 13. 
4. 3. Certified device in Google page. 
5. 4. Installed GApps.

When I tried to use it, I had a problem that when I tried to log in, it did not even show me anything, then just an empty color; after some time it dropped me back. Same problem in Play market log page.  There's examples photos: 

![image](https://github.com/user-attachments/assets/0b76715b-f885-45d2-bd09-ff2a1553ec81)
![image](https://github.com/user-attachments/assets/9cbf7ee4-e292-489a-889a-16f37712f9b9)

When I launch "waydroid show-full-ui" it doesn't show any error

**Comment by supechicken** [comment]
Hello, this should be fixed in the latest [ATV 13 image (20241208)](https://github.com/supechicken/waydroid-androidtv-build/releases/tag/20241208).
