### ISSUE TITLE
Pending loop (Can't donwload apps)

### ISSUE THREAD

**Issue by FelixOnly** [supechicken/waydroid-androidtv-build#15]
![image](https://github.com/user-attachments/assets/d22c96b5-949a-4fd9-9e30-73da3a5528db)

Hello, thank you for the new release. I tried the new version, and I have a problem with downloading apps. I manage to log in without any problems, but downloading is not working. 

I tried cleaning the cache in Play Market and Google services; it didn't help.

**Comment by supechicken** [comment]
Maybe try [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore) as an alternative?

(I have also encountered this and can't find out why. It still doesn't work after updating both Play store and Play service)

**Comment by FelixOnly** [comment]
Sounds okay for me, but how I can install it there?

**Comment by supechicken** [comment]
Hi, this is fixed on the latest build ([20241215](https://github.com/supechicken/waydroid-androidtv-build/releases/tag/20241215)), along with updated GApps install instructions.

**Comment by FelixOnly** [comment]
I installed your new realese and everything is working, thank you!
