### ISSUE TITLE
unable to build vendor.img for Android 13 TV

### ISSUE THREAD

**Issue by ryanrudolfoba** [supechicken/waydroid-androidtv-build#16]
Thank you for your guide - I was able to build the system.img for Android 13 TV using your patches and guide.

However I'm having difficulty building vendor.img.

About 95% completed it dies. On the error message it complains that it cant find the following -

lua
libarchive
libxml2

I'm building using CentOS Stream 9 and those packages are already installed but the build environment still not able to find them. I was thinking maybe its old version since I'm using CentOS 9. So I uninstalled lua and manually installed the latest version from lua.org

Ran the script again and it continued for a bit, then died again. When I ran it again it now complains -
`error: vendor/lineage/build/soong/Android.bp:24:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'`

Any suggestions on how to troubleshoot this further?

**Comment by ryanrudolfoba** [comment]
### additional logs showing the missing items -

> Run-time dependency lua54 found: NO (tried pkgconfig and cmake)
Run-time dependency lua53 found: NO (tried pkgconfig and cmake)
Run-time dependency lua52 found: NO (tried pkgconfig and cmake)
Run-time dependency lua found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency lua54
Downloading lua source from https://www.lua.org/ftp/lua-5.4.6.tar.gz
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://www.lua.org/ftp/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://www.lua.org/ftp/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://www.lua.org/ftp/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://www.lua.org/ftp/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://www.lua.org/ftp/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
Downloading lua source from https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?
Subproject  lua is buildable: NO (disabling)
Dependency lua54 from subproject lua found: NO (subproject failed to configure)
Run-time dependency libarchive found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libarchive
Downloading libarchive source from https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
Downloading libarchive source from https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?
Subproject  libarchive is buildable: NO (disabling)
Dependency libarchive from subproject libarchive found: NO (subproject failed to configure)
Run-time dependency libxml-2.0 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libxml-2.0
Downloading libxml2 source from https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.6.tar.xz
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
Downloading libxml2 source from https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
WARNING: failed to download with error: could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?. Trying after a delay...
<urlopen error [Errno -2] Name or service not known>
could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?
Subproject  libxml2 is buildable: NO (disabling)
Dependency libxml-2.0 from subproject libxml2 found: NO (subproject failed to configure)
Program gzip found: YES (/usr/bin/gzip)
Run-time dependency libconfig found: NO (tried pkgconfig and cmake)
ncursesw6-config found: NO
Run-time dependency curses found: NO (tried pkgconfig, pkgconfig, pkgconfig, pkgconfig, config-tool and system)


### subprojects that failed
>  Subprojects
    libarchive                   : NO
                                   could not get https://github.com/mesonbuild/wrapdb/releases/download/libarchive_3.7.2-3/libarchive-3.7.2.tar.xz is the internet available?
    libxml2                      : NO
                                   could not get https://github.com/mesonbuild/wrapdb/releases/download/libxml2_2.11.6-1/libxml2-2.11.6.tar.xz is the internet available?
    llvm                         : YES
    lua                          : NO
                                   could not get https://github.com/mesonbuild/wrapdb/releases/download/lua_5.4.6-4/lua-5.4.6.tar.gz is the internet available?

### and finally it quits
>ERROR: Could not detect Ninja v1.8.2 or newer
A full log can be found at /home/ryanrudolf/atv/out/target/product/waydroid_x86_64/obj/MESON_MESA3D/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
17:25:21 ninja failed with: exit status 1
failed to build some targets (02:49:11 (hh:mm:ss))
[ryanrudolf@plex atv]$


### the things it is complaining that are missing is already instealled as shown here -

>[ryanrudolf@plex ~]$ whereis lua
lua: /usr/bin/lua /usr/lib64/lua /usr/local/bin/lua /usr/local/lib/lua /usr/share/lua
[ryanrudolf@plex ~]$
[ryanrudolf@plex ~]$ rpm -qa | grep libxml2
libxml2-2.9.13-6.el9.x86_64
[ryanrudolf@plex ~]$
[ryanrudolf@plex ~]$ rpm -qa | grep libarchive
libarchive-3.5.3-4.el9.x86_64
[ryanrudolf@plex ~]$
[ryanrudolf@plex ~]$ rpm -qa | grep curses
ncurses-base-6.2-10.20210508.el9.noarch
ncurses-libs-6.2-10.20210508.el9.x86_64
ncurses-c++-libs-6.2-10.20210508.el9.x86_64
ncurses-devel-6.2-10.20210508.el9.x86_64
ncurses-6.2-10.20210508.el9.x86_64
ncurses-compat-libs-6.2-8.20210508.1.el9.x86_64
[ryanrudolf@plex ~]$

**Comment by supechicken** [comment]
The `-devel` version of those packages is required for compilation, some of them are listed below (I am not sure the name of packages below are correct since I have no experience with `rpm` 😅, you can refer to the `aosp-devel` and `lineageos-devel` package in AUR for a complete dependency list that are required):
```shell
libxml2-devel
libarchive-devel
ninja
lua-devel
python-mako
python-setuptools
```

**Comment by ryanrudolfoba** [comment]
Thank you that was it!

For anyone else struggling building using CentOS, I had to grab lua-devel from the CodeReady repo. Need to enable that repo first -

`dnf config-manager --set-enabled crb`

Build is progressing again and fingers crossed I hope no more errors.
