### ISSUE TITLE
Youtube app speed not available on this device

### ISSUE THREAD

**Issue by ytzeng1** [supechicken/waydroid-androidtv-build#4]
Hi @supechicken,

Thank you so much for sharing this! It's almost perfect for HTPC frontend. 

One thing that I noticed is that the youtube app does not allow adjusting playback speed.
![image](https://github.com/user-attachments/assets/874bf307-d784-4f48-aa53-49cb361e31cd)
Besides, not sure if it is related, but the max video quality is limited to 1080p.  

Best,

**Comment by supechicken** [comment]
Sorry for the late reply!

I tried installing the TV app on my phone and I am getting the same result. (so it is probably a limitation from Google)

You might try spoofing the device model to a certificated Android TV Box to "trick" the Youtube app, like this:

https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/blob/bdc30b0fc541ff0655a6f8fa277c697d8148927e/steamos-waydroid-installer.sh#L355-L387

**Comment by ytzeng1** [comment]
Thanks for your suggestions. I'll dig around.
