### ISSUE TITLE
Add VAAPI drivers for AMD

### ISSUE THREAD

**Issue by rijnhard** [supechicken/waydroid-androidtv-build#7]
Any chance the image can be updated with VAAPi drivers for AMD?

```sh
sudo waydroid logcat | grep -i vaapi
10-02 19:30:30.978   105  3537 D HWACCEL : ffmpeg_hwaccel_init: 0xf74b1000 [h264], hw device = vaapi
10-02 19:30:31.005   105  3537 I FFMPEG  : [h264 @ 0xf74b1000] Failed setup for format vaapi: hwaccel initialisation returned error.
10-02 19:33:09.880   105  3749 D HWACCEL : ffmpeg_hwaccel_init: 0xf74b6000 [h264], hw device = vaapi
10-02 19:33:09.881   105  3749 I FFMPEG  : [h264 @ 0xf74b6000] Failed setup for format vaapi: hwaccel initialisation returned error.
```

This PR may be useful:
https://github.com/waydroid/android_device_waydroid_waydroid/pull/3

**Comment by supechicken** [comment]
The VAAPI drivers for AMD GPUs should be enabled by that PR, and that PR is [merged into my fork](https://github.com/Waydroid-ATV/android_device_waydroid_waydroid/commit/4cc6250e4010898e92117872899ee8b7b8a6ecaf) already. (which means the driver is included in the image already)

From the log above, it seems that the VAAPI driver is throwing some errors, probably something wrong with FFmpeg/Mesa's implementation, not something I can easily deal with😅

**Comment by supechicken** [comment]
See https://github.com/supechicken/waydroid-androidtv-build/issues/8#issuecomment-2392119664
